version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: genealogy-laravel-app
    container_name: genealogy-laravel-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    # volumes:
    #   - ./:/var/www/html
    environment:
      - DB_HOST=db
      - DB_DATABASE=genealogy
      - DB_USERNAME=root
      - DB_PASSWORD=secret
      - APP_KEY=base64:Mf9KyiITcghKIdkkmCS5i0BJD0nJBGct74UGShqFGrg=
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: genealogy-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: genealogytwo
      MYSQL_ROOT_PASSWORD: 
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
